### ISSUE TITLE
Probleme compilation

### ISSUE THREAD

**Issue by mahautlatinis** [Velovo/ft_irc#2]
Hello ! Je n'arrive pas a compiler le projet ni sur mon mac perso, ni sur la VM :(

**Comment by avan-pra** [comment]
Hello, pour mac je n'ai pas trop d’idée mais si tu pouvais inclure un screen de l'erreur de compil sous la vm je suis preneur, pas de problème de mon cote sous vm xubuntu de 42 ou debian 11, tu as install libssl-dev comme indiqué dans le [readme](https://github.com/avan-pra/ft_irc#Install) ?

Essaye de lancer avec `make 42` si tu tente de compiler direct sous macos (en ayant install libssl-dev avant) mais je garantie rien

Essaye de lancer dans un docker sinon ?
Sous debian:bullseye ca marche TB avec cette ligne:

`
cd /tmp && apt update && apt install -y git make clang libssl-dev && git clone https://github.com/avan-pra/ft_irc.git && cd ft_irc && make
`

**Comment by mahautlatinis** [comment]
Hello, desolee d'avoir mis du temps a repondre ! C'est bon j'ai reussi sur la VM merci  !
